### ISSUE TITLE
Thesis TODO

### ISSUE THREAD

**Issue by ryutasato** [RyutaSato/ml-study-archive-rsato#17]
## 未完成のChapter

- [x] 1.2 構成
- [x] 3.2 オートエンコーダ
- [x] 3.3 AE特徴量
- [x] 4 index
- [x] 4.1 概要
- [x] 4.4 学習方法
- [x] 交差検証
- [x] optuna
  - パラメータ設定
- [x] データセットの詳細: kdd99
- [x] データセットの詳細: kdd99_dropped
- [x] データセットの詳細: creditcardfraud
- [x] データセットの詳細: ecoli
- [x] データセットの詳細: optical_digits
- [x] データセットの詳細: satimage
- [x] データセットの詳細: pen_digits
- [x] データセットの詳細: abalone
- [x] データセットの詳細: sick_euthyroid
- [x] データセットの詳細: spectrometer
- [x] データセットの詳細: car_eval_34
- [x] データセットの詳細: isolet
- [x] データセットの詳細: us_crime
- [x] データセットの詳細: yeast_ml8
- [x] データセットの詳細: scene
- [x] データセットの詳細: libras_move
- [x] データセットの詳細: thyroid_sick
- [x] データセットの詳細: coil_2000
- [x] データセットの詳細: arrhythmia
- [x] データセットの詳細: solar_flare_m0
- [x] データセットの詳細: oil
- [x] データセットの詳細: car_eval_4
- [x] データセットの詳細: wine_quality
- [x] データセットの詳細: letter_img
- [x] データセットの詳細: yeast_me2
- [x] データセットの詳細: webpage
- [x] データセットの詳細: ozone_level
- [x] データセットの詳細: mammography
- [x] データセットの詳細: protein_homo
- [x] データセットの詳細: abalone_19

- [x] 学習モデルの説明: ロジスティック回帰
- [x] 学習モデルの説明: SVM
- [x] 学習モデルの説明: Random forest
- [x] 学習モデルの説明: Light GBM
- [x] 学習モデルの説明: Multi Perceptron

- [x] 4.8 実験条件
- [x] ワークフローの検証内容と結果の参照先
- [x] プログラムの固定パラメータの設定・ライブラリのバージョン
- [x] 実験環境　図も入れる
- [x] 実験結果: AE 特徴量を加えることで，分類精度が向上するかどうかの検証
- [x] 実験結果: AutoEncoderが学習するデータを特定のクラスに偏らせることが，分類精度に影響するかどうかの検証
- [x] 実験結果: AutoEncoderの隠れ層の構成が，分類精度に影響するかどうかの検証
- [x] 実験結果: AE特徴量の数が，分類精度に影響するかどうかの検証
- [x] 実験結果: 入力データの前処理によって，分類精度に影響するかどうかの検証
- [x] 実験結果: オートエンコーダに学習させるデータの種類によって，分類精度に影響するかどうかの検証

- [x] 考察
- [x] 終わりに
- [x] 謝辞
- [x] 表

## 修正箇所

- [x] rename AutoEncoder -> オートエンコーダ(Autoencoder)
- [x] 機械学習フロー図の文字切れ・サイズ調整

## 参照元の追加

- [x] k-NN
- [x] Logistic Regression
- [x] XGBoost
- [x] SMOTE
- [x] optical_digits
- [x] kdd99
- [x] creditcardfraud

### optuna なし
- [x] svm normalize=True 

### optuna あり
TODO: 未記入

**Comment by ryutasato** [comment]
- [x] 前結果のTEXへの書き出しプログラム

**Comment by ryutasato** [comment]
- [x] オートエンコーダ画像の準備
